#figure(
align(center)[#table(
  columns: 2,
  align: (col, row) => (left,right,).at(col),
  inset: 6pt,
  [#strong[Metric];], [#strong[Value];],
  [Nodes],
  [68240],
  [Links],
  [237264],
  [Density],
  [0.0001],
  [Mean Degree],
  [6.95],
  [SD Degree],
  [70.37],
  [Reciprocity],
  [0.13],
  [Assortativity \(Degree)],
  [-0.10],
  [Average Shortest Path \(sampled)],
  [4.35],
  [Diameter \(sampled)],
  [47],
  [Clustering Coefficient],
  [0.1267],
  [Max K-Core],
  [24],
)]
)
